bookr/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from bookr.views import profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('reviews.urls')),
    path('accounts/', include(('django.contrib.auth.urls', 'auth'), namespace='accounts')),
    path('accounts/profile/', profile, name='profile'),
    path('filter_demo/', include('filter_demo.urls')),
    path('book_management/', include('book_management.urls'))

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reviews/models.py
import re
from django.contrib import auth
from django.conf import settings
from django.db import models

class Publisher(models.Model):
    """A company that publishes books."""
    name = models.CharField(max_length=50, help_text="The name of the Publisher.")
    website = models.URLField(help_text="The Publisher's website.")
    email = models.EmailField(help_text="The Publisher's email address.")

    def __str__(self):

        return self.name

class Book(models.Model):
    """A published book."""
    title = models.CharField(max_length=70, help_text='The title of the book.')
    publication_date = models.DateField(verbose_name='Date the book was published.')
    isbn = models.CharField(max_length=20, verbose_name='ISBN number of the book.')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    contributors = models.ManyToManyField('Contributor', through='BookContributor')
    cover = models.ImageField(upload_to='book_covers/', null=True, blank=True)
    sample = models.FileField(upload_to='book_samples/', null=True, blank=True)

    def __str__(self):

        return f'{self.title} ({self.isbn})'

    def average_rating_number_of_reviews(self):

        reviews = self.review_set.all()

        if not reviews:

            return None, 0
        
        book_rating = sum([review.rating for review in reviews]) / len(reviews)

        return round(book_rating), len(reviews)

    def contributors_names(self):

        contributors = self.contributors.all()
        contributors_names = [contributor.complete_name() for contributor in contributors]

        return ', '.join(contributors_names)

class Contributor(models.Model):
    """A contributor to a Book, e.g. author, editor, co-author."""
    first_names = models.CharField(max_length=50, help_text="The contributor's first name or names.")
    last_names = models.CharField(max_length=50, help_text="The contributor's last name or names.")
    email = models.EmailField(help_text="The contact email for the contributor.")

    def initialled_name(self):
        """Treatment concatenating contributor's last names with , and initial firt names with upper case."""
        
        initial_first_names = ''.join([
            name[0].upper() for name in self.first_names.split(' ')
        ])

        return ', '.join([self.last_names, initial_first_names])

    def complete_name(self):
        """Treatment concatenating first and last names, configuring the complete name of a contributor."""

        return ' '.join([self.first_names, self.last_names])

    def number_of_contributions(self):
        """Return the number of contributions for this contributor."""

        return Book.objects.filter(contributors__first_names=self.first_names).count()

    def __str__(self):

        return self.initialled_name()

class BookContributor(models.Model):
    """Estabilish many to many relationship between Books and Contributors"""
    class ContributionRole(models.TextChoices):
        AUTHOR = 'AUTHOR', 'Author'
        CO_AUTHOR = 'CO_AUTHOR', 'Co-Author'
        EDITOR = 'EDITOR', 'Editor'

    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    contributor = models.ForeignKey(Contributor, on_delete=models.CASCADE)
    role = models.CharField(
        verbose_name='The role this contributor had in the book.', 
        choices=ContributionRole.choices, 
        max_length=20
    )

class Review(models.Model):
    """Reviews added by users"""
    content = models.TextField(help_text='The review text.')
    rating = models.IntegerField(help_text='The rating the reviewer has given.')
    date_created = models.DateTimeField(auto_now=True, help_text='The date and time the review was created.')
    date_edited = models.DateTimeField(null=True, help_text='The date and time the review was last edited.')
    creator =  models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, help_text='The Bok that tis review is for.')

templates/base.html
{% load bootstrap4 %}
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        {% bootstrap_css %}
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'main.css' %}">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Libre+Baskerville|Source+Sans+Pro&display=swap">
        {% block title%}
            <title>Book Review</title>
        {% endblock %}
        
    </head>
    <body>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top">
            <a class="navbar-brand" href="/">
                {% block brand %}
                    <img src="{% static 'logo.png' %}">                
                {% endblock %}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/books/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/logout">Logout</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="/accounts/login">Login</a>
                        </li>
                    {% endif %}
                </ul>
                <form class="form-inline my-2 my-lg-0" action="{% url 'book_search' %}">
                    <input class="form-control mr-sm-2" type="search" name="search" value="" placeholder="Search" aria-label="Search" minlength="3">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
                {% if user.is_authenticated %}

                    <a class="nav-link danger" href="/accounts/profile">User: {{ request.user.first_name }}</a>

                {% endif %}
            </div>
        </nav>
        <div class="container-fluid">
            {% for message in messages %}
                <div class="alert alert-{% if message.level_tag == 'error' %}danger{% else %}{{ message.level_tag }}{% endif %}" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
            {% block content %}
                <h3>Welcome to Bookr!</h3>
            {% endblock %}
        </div>
        <!-- Copyright -->
        <footer class="page-footer font-small blue">
            <div class="footer-copyright text-center py-3">© 2020 Copyright:
                <a href="https://www.packtpub.com">Packt Publications</a>
                <p>Website by: Packt Publications</p>
                <p>Contact Information: <a href="mailto:email@example.com">email@example.com</a></p>
            </div>
        </footer>
        <!-- Copyright -->
    </body>
</html>

templates/example_form_model_admin.html
<form method="post" id="publisher_form" novalidate><input type="hidden" name="csrfmiddlewaretoken" value="moJ4Re9N34bImvtY4j1tuhQQpbac8yo6zxjqqsbO5TmcBBx8s6zHhQyHObaVoYiz">
    <div>
        <fieldset class="module aligned ">
            <div class="form-row field-name">
                    <div>
                            <label class="required" for="id_name">Name:</label>
                                <input type="text" name="name" value="Pocket Books" class="vTextField" maxlength="50" required id="id_name">
                            <div class="help">The name of the Publisher.</div>
                    </div>
            </div>
            <div class="form-row field-website">
                    <div>
                            <label class="required" for="id_website">Website:</label>
                                <p class="url">Currently: <a href="https://pocketbookssampleurl.com">https://pocketbookssampleurl.com</a><br>Change: <input type="url" name="website" value="https://pocketbookssampleurl.com" class="vURLField" maxlength="200" required id="id_website"></p>
                            <div class="help">The Publisher's website.</div>
                    </div>
            </div>
            <div class="form-row field-email">
                    <div>
                            <label class="required" for="id_email">Email:</label>
                                <input type="email" name="email" value="pocketbook@example.com" class="vTextField" maxlength="254" required id="id_email">
                            <div class="help">The Publisher's email address.</div>
                    </div>
            </div>
        </fieldset>
        <div class="submit-row">
        <input type="submit" value="Save" class="default" name="_save">
            <p class="deletelink-box"><a href="/admin/reviews/publisher/9/delete/" class="deletelink">Delete</a></p>
        <input type="submit" value="Save and add another" name="_addanother">
        <input type="submit" value="Save and continue editing" name="_continue">
        </div>
            <script 
                id="django-admin-form-add-constants"
                src="/static/admin/js/change_form.js"
                async>
            </script>
            <script 
                id="django-admin-prepopulated-fields-constants"
                src="/static/admin/js/prepopulate_init.js"
                data-prepopulated-fields="[]">
            </script>
    </div>
</form>

templates/profile.html
{% extends 'base.html' %}

{% block title %}Bookr{% endblock %}

{% block content %}
    <style>
        .flexrow {
        display: flex;
        border: 2px black;
        }

        .flexrow > div {
            flex: 1;
        }

        .infocell {
            border: 2px solid green;
            border-radius: 5px 25px;
            background-color: white;
            padding: 5px;
            margin: 20px 5px 5px 5px;
        }
    </style>

    <div class="flexrow">
        <div class="infocell">
            <h2>Profile</h2>
            <p>                
                Username: {{ request.user.username }} <br>
                Name: {{ request.user.first_name }} <br>
                Date Joined: {{ request.user.date_joined }} <br>
                Email: {{ request.user.email }} <br>
                Last Login: {{ request.user.last_login }} <br>
            </p>
        </div>
        <div class="infocell">
            <h2>Viewed Books</h2>
            <p>
                {% for book_id, book_title in request.session.viewed_books %}
                <a href="{% url 'book_details' book_id %}">{{ book_title }}</a><br>
                {% empty %}
                    No recently viewed books found.
                {% endfor %}
            </p>
        </div>
        <div class="infocell">
            <h2>Search History</h2>
            <p>
                {% for search_text, search_in in request.session.search_history %}
                <a href="/book_search?search={{ search_text }}&search_in={{ search_in }}">{{ search_text }} ({{ search_in }})</a><br>
                {% empty %}
                    No recently viewed books found.
                {% endfor %}
            </p>
        </div>
        <div class="infocell">
            <h2>Read Books</h2>
            <p>
                {% load profile_tags %}
                {% books_list request.user.username %}
            </p>
        </div>
    </div>
{% endblock %}